services:
  monopoly-mongodb:
    container_name: monopoly-mongodb
    image: mongo
    expose:
      - "27017"
    networks:
      - monopoly
    volumes:
      - ./mongodbdata:/data/db
    restart: unless-stopped

  monopoly-web:
    container_name: monopoly-web-2026
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://eecamp-monopoly-2026.ntuee.org/api
    expose:
      - "2022"
    ports:
      - "2022:2022"
    depends_on:
      - monopoly-mongodb
    environment:
      MONGO_URL: mongodb://monopoly-mongodb/monopoly
      WEB_DOMAIN: eecamp-monopoly-2026.ntuee.org
    tty: true
    stdin_open: true
    networks:
      - monopoly
      - nginx
    restart: unless-stopped

networks:
  nginx:
    external: true
  monopoly: